In [1]:
import pandas as pd
loan_df = pd.read_csv("Loan.csv")
loan_df

,ApplicationDate,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,2018-01-01,45,39948,617,Employed,Master,22,13152,48,Married,...,3329.000000,0.724972,11,126928,0.199652,0.227590,419.805992,0.181077,0,49.0
1,2018-01-02,38,39709,628,Employed,Associate,15,26045,48,Single,...,3309.083333,0.935132,3,43609,0.207045,0.201077,794.054238,0.389852,0,52.0
2,2018-01-03,47,40724,570,Employed,Bachelor,26,17627,36,Married,...,3393.666667,0.872241,6,5205,0.217627,0.212548,666.406688,0.462157,0,52.0
3,2018-01-04,58,69084,545,Employed,High School,34,37898,96,Single,...,5757.000000,0.896155,5,99452,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,2018-01-05,37,103264,594,Employed,Associate,17,9184,36,Married,...,8605.333333,0.941369,5,227019,0.197184,0.175990,330.179141,0.070210,1,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2072-09-29,44,30180,587,Employed,High School,19,24521,36,Married,...,2515.000000,0.826217,1,55327,0.216021,0.195574,905.767712,0.627741,0,55.0
19996,2072-09-30,56,49246,567,Employed,Associate,33,25818,36,Married,...,4103.833333,0.816618,3,64002,0.227318,0.199168,958.395633,0.334418,0,54.0
19997,2072-10-01,44,48958,645,Employed,Bachelor,20,37033,72,Married,...,4079.833333,0.887216,3,103663,0.229533,0.226766,945.427454,0.357227,0,45.0
19998,2072-10-02,60,41025,560,Employed,High School,36,14760,72,Married,...,3418.750000,0.843787,5,10600,0.249760,0.264873,411.168284,0.408678,0,59.0
19999,2072-10-03,20,53227,574,Employed,Associate,0,32055,48,Married,...,4435.583333,0.853801,5,41372,0.240055,0.242693,1049.830407,0.298006,0,59.0

In [2]:
loan_df['EmploymentStatus'].unique()

array(['Employed', 'Self-Employed', 'Unemployed'], dtype=object)

In [3]:
loan_df.columns

Index(['ApplicationDate', 'Age', 'AnnualIncome', 'CreditScore',
       'EmploymentStatus', 'EducationLevel', 'Experience', 'LoanAmount',
       'LoanDuration', 'MaritalStatus', 'NumberOfDependents',
       'HomeOwnershipStatus', 'MonthlyDebtPayments',
       'CreditCardUtilizationRate', 'NumberOfOpenCreditLines',
       'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory',
       'LoanPurpose', 'PreviousLoanDefaults', 'PaymentHistory',
       'LengthOfCreditHistory', 'SavingsAccountBalance',
       'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities',
       'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth',
       'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment',
       'TotalDebtToIncomeRatio', 'LoanApproved', 'RiskScore'],
      dtype='object')

In [4]:
df = loan_df.copy()
selected_columns = [
    'Age','CreditScore','EmploymentStatus','EducationLevel',
    'LoanAmount','LoanDuration','CreditCardUtilizationRate',
    'BankruptcyHistory','PreviousLoanDefaults','LengthOfCreditHistory',
    'MonthlyIncome','NetWorth','InterestRate','RiskScore','LoanApproved'
]

df = df[selected_columns]
df.sample(20)

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
12308,46,611,Employed,Bachelor,30214,36,0.387678,0,0,25,2969.166667,94451,0.222109,50.0,0
13586,32,622,Employed,Master,30129,24,0.077236,0,0,21,2329.000000,10094,0.164495,48.0,0
14284,35,565,Employed,High School,30771,84,0.138826,0,0,10,1334.916667,95569,0.310777,49.0,0
4616,53,615,Employed,Master,12880,60,0.285167,0,0,4,1963.750000,7624,0.178322,54.0,0
15037,23,568,Employed,Associate,13809,48,0.167855,0,0,19,2220.000000,124328,0.206711,55.0,0
16716,49,585,Employed,Bachelor,30993,96,0.066407,0,0,20,3899.583333,3781,0.258579,52.0,0
7141,44,522,Employed,Bachelor,14930,24,0.219639,0,0,20,2640.500000,80770,0.223394,53.0,0
16753,32,577,Employed,Bachelor,13795,48,0.152506,0,1,4,4839.250000,9484,0.248608,62.0,0
11922,41,584,Employed,High School,27139,36,0.117333,0,0,26,4765.750000,87969,0.190504,40.8,1
13372,42,488,Employed,Doctorate,17659,84,0.298394,0,0,25,4151.583333,40587,0.257282,44.0,1
4035,51,492,Employed,Bachelor,14125,72,0.222028,0,0,11,7305.250000,38078,0.226500,45.6,1
12968,43,525,Employed,High School,27062,36,0.195539,0,0,4,6281.750000,602875,0.213759,36.8,1
7684,51,589,Employed,High School,14529,36,0.174547,0,0,4,3535.500000,142889,0.242447,53.0,0
19647,22,565,Employed,Bachelor,29979,48,0.328132,0,0,2,2584.500000,171931,0.228387,51.0,0
15692,37,609,Employed,Master,49488,60,0.052128,0,1,12,5128.833333,7051,0.299986,56.0,0
11275,49,639,Employed,Master,10418,24,0.247945,0,0,6,2424.833333,171596,0.164936,55.0,0
2758,26,616,Employed,Doctorate,24097,72,0.593758,0,0,9,3857.000000,216225,0.267007,50.0,0
546,46,541,Employed,Associate,8798,36,0.143458,1,0,3,3664.500000,2198,0.215028,67.0,0
10273,51,644,Employed,Bachelor,35696,36,0.036070,0,0,3,8270.500000,27183,0.208845,48.0,0
12836,27,423,Employed,Bachelor,26832,24,0.383193,0,0,22,8143.916667,97512,0.302293,49.0,0

Ordinal Encoding

In [5]:
df['EmploymentStatus'] = df['EmploymentStatus'].map({'Unemployed':0,'Self-Employed':1,'Employed':2})
df['EducationLevel']=df['EducationLevel'].map({'High School':0,'Associate':1,'Bachelor':2,'Master':3,'Doctorate':4})

df

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
0,45,617,2,3,13152,48,0.354418,0,0,9,3329.000000,126928,0.227590,49.0,0
1,38,628,2,1,26045,48,0.087827,0,0,9,3309.083333,43609,0.201077,52.0,0
2,47,570,2,2,17627,36,0.137414,0,0,22,3393.666667,5205,0.212548,52.0,0
3,58,545,2,0,37898,96,0.267587,0,0,10,5757.000000,99452,0.300911,54.0,0
4,37,594,2,1,9184,36,0.320535,0,0,27,8605.333333,227019,0.175990,36.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,44,587,2,0,24521,36,0.101288,0,0,7,2515.000000,55327,0.195574,55.0,0
19996,56,567,2,1,25818,36,0.471818,0,0,28,4103.833333,64002,0.199168,54.0,0
19997,44,645,2,2,37033,72,0.216596,0,0,8,4079.833333,103663,0.226766,45.0,0
19998,60,560,2,0,14760,72,0.364758,0,0,13,3418.750000,10600,0.264873,59.0,0
19999,20,574,2,1,32055,48,0.536411,0,0,14,4435.583333,41372,0.242693,59.0,0

Handling Skewness Using Log

In [6]:
# Calculate skewness for each column
skewness = df.skew()

# Sort the skewness values in ascending order
sorted_skewness = skewness.sort_values(ascending=True)

# Displays the sorted skewness values
print(sorted_skewness)

EmploymentStatus            -2.455244
CreditScore                 -0.596727
RiskScore                   -0.162062
LengthOfCreditHistory        0.002989
Age                          0.185964
EducationLevel               0.273155
InterestRate                 0.485491
CreditCardUtilizationRate    0.601131
LoanDuration                 0.651330
LoanApproved                 1.224086
LoanAmount                   1.833688
MonthlyIncome                1.992929
PreviousLoanDefaults         2.665941
BankruptcyHistory            4.017672
NetWorth                     5.599844
dtype: float64

In [7]:
import numpy as np
# List of features to transform (continues numeric columns with more than 1 skewness value)
features_to_log1p = ['LoanAmount','MonthlyIncome','NetWorth']

# Apply log1p transformation
df[features_to_log1p] = df[features_to_log1p].apply(np.log1p)
df

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
0,45,617,2,3,9.484405,48,0.354418,0,0,9,8.110728,11.751383,0.227590,49.0,0
1,38,628,2,1,10.167619,48,0.087827,0,0,9,8.104729,10.683042,0.201077,52.0,0
2,47,570,2,2,9.777244,36,0.137414,0,0,22,8.129961,8.557567,0.212548,52.0,0
3,58,545,2,0,10.542680,96,0.267587,0,0,10,8.658345,11.507440,0.300911,54.0,0
4,37,594,2,1,9.125327,36,0.320535,0,0,27,9.060254,12.332793,0.175990,36.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,44,587,2,0,10.107326,36,0.101288,0,0,7,7.830426,10.921034,0.195574,55.0,0
19996,56,567,2,1,10.158866,36,0.471818,0,0,28,8.319920,11.066685,0.199168,54.0,0
19997,44,645,2,2,10.519592,72,0.216596,0,0,8,8.314056,11.548910,0.226766,45.0,0
19998,60,560,2,0,9.599744,72,0.364758,0,0,13,8.137323,9.268704,0.264873,59.0,0
19999,20,574,2,1,10.375240,48,0.536411,0,0,14,8.397640,10.630384,0.242693,59.0,0

Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
df_standardized = df.copy()
columns_to_standardize = [
    'Age', 'CreditScore', 'LoanAmount', 'LoanDuration',
    'CreditCardUtilizationRate', 'LengthOfCreditHistory',
    'MonthlyIncome', 'NetWorth', 'InterestRate'
]

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling
df_standardized[columns_to_standardize] = scaler.fit_transform(df_standardized[columns_to_standardize])

df_standardized.head()

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate,RiskScore,LoanApproved
0,0.451489,0.890021,2,3,-1.014008,-0.245578,0.425792,0,0,-0.711630,-0.324366,1.020941,-0.272968,49.0,0
1,-0.150795,1.105724,2,1,0.343015,-0.245578,-1.242602,0,0,-0.711630,-0.334247,0.287206,-0.901165,52.0,0
2,0.623571,-0.031618,2,2,-0.432362,-0.732113,-0.932273,0,0,0.841287,-0.292687,-1.172566,-0.629370,52.0,0
3,1.570017,-0.521852,2,0,1.087972,1.700559,-0.117617,0,0,-0.592175,0.577602,0.853401,1.464331,54.0,0
4,-0.236835,0.439006,2,1,-1.727221,-0.732113,0.213746,0,0,1.438563,1.239575,1.420252,-1.495584,36.0,1

In [9]:
def remove_outliers_iqr(df,exclude_columns):
  # Loop through numeric columns
  for column in df.select_dtypes(include=['number']):
    if column in exclude_columns:
      continue # Skip excluded columns
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    # Define outlier bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    # Filter out the outliers
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
  return df
# Remove Outliers
df_standardized=remove_outliers_iqr(df,columns_to_standardize)

# Print shapes of data before and after removing outliers
print('Shape of data before removing outliers:',df.shape)
print('Shape of data after removing outliers:',df_standardized.shape)
print('Number of outlier removed:',df.shape[0]-df_standardized.shape[0])

Shape of data before removing outliers: (20000, 15)
Shape of data after removing outliers: (14485, 15)
Number of outlier removed: 5515

In [10]:
x=df_standardized.drop(['RiskScore','LoanApproved'],axis=1)
y=df_standardized[['RiskScore']]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

print('Shape of Training Features: ',x_train.shape)
print('Shape of Testing Features: ',x_test.shape)
print('Shape of Training Target: ',y_train.shape)
print('Shape of Testing Target: ',y_test.shape)

Shape of Training Features:  (11588, 13)
Shape of Testing Features:  (2897, 13)
Shape of Training Target:  (11588, 1)
Shape of Testing Target:  (2897, 1)

In [12]:
from lightgbm import LGBMRegressor
reg_model = LGBMRegressor()
reg_model.fit(x_train, y_train.values.ravel())

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000265 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1621
[LightGBM] [Info] Number of data points in the train set: 11588, number of used features: 10
[LightGBM] [Info] Start training from score 48.969123

LGBMRegressor()

In [13]:
from sklearn.metrics import r2_score

y_pred = reg_model.predict(x_test)
print(r2_score(y_pred,y_test))

0.6307375156512296

In [14]:
# to get the order of features trained
x_train.columns

Index(['Age', 'CreditScore', 'EmploymentStatus', 'EducationLevel',
       'LoanAmount', 'LoanDuration', 'CreditCardUtilizationRate',
       'BankruptcyHistory', 'PreviousLoanDefaults', 'LengthOfCreditHistory',
       'MonthlyIncome', 'NetWorth', 'InterestRate'],
      dtype='object')

In [15]:
new_input = {
    'Age': 30,
    'CreditScore': 700,
    'EmploymentStatus': 'Employed',
    'EducationLevel': 'Master',
    'LoanAmount': 15000,
    'LoanDuration': 24,
    'CreditCardUtilizationRate': 0.3,
    'BankruptcyHistory': 0,
    'PreviousLoanDefaults': 0,
    'LengthOfCreditHistory': 5,
    'MonthlyIncome': 4500,
    'NetWorth': 20000,
    'InterestRate': 10.5
}

input_df = pd.DataFrame([new_input])
status_map = {'Unemployed': 0, 'Self-Employed': 1, 'Employed': 2}
edu_map = {'High School': 0, 'Associate': 1, 'Bachelor': 2, 'Master': 3, 'Doctorate': 4}
input_df['EmploymentStatus'] = input_df['EmploymentStatus'].map(status_map)
input_df['EducationLevel'] = input_df['EducationLevel'].map(edu_map)

input_df

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate
0,30,700,2,3,15000,24,0.3,0,0,5,4500,20000,10.5

In [16]:
# List of features to transform (Continues numeric coloumns with more than 1 skewness value)
features_to_log1p = ['LoanAmount', 'MonthlyIncome', 'NetWorth']

# Apply log1p transformation
input_df[features_to_log1p] = input_df[features_to_log1p].apply(np.log1p)
input_df

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate
0,30,700,2,3,9.615872,24,0.3,0,0,5,8.412055,9.903538,10.5

In [17]:
# Define the columns to standardize (Continues numeric coloumns)
num_cols_to_standardize = [
    'Age', 'CreditScore', 'LoanAmount', 'LoanDuration',
    'CreditCardUtilizationRate', 'LengthOfCreditHistory',
    'MonthlyIncome', 'NetWorth', 'InterestRate'
]

# Apply standardization only to selected numeric columns
input_df[num_cols_to_standardize] = scaler.transform(input_df[num_cols_to_standardize])

# df_standardized is now ready, with only selected columns standardized
input_df

,Age,CreditScore,EmploymentStatus,EducationLevel,LoanAmount,LoanDuration,CreditCardUtilizationRate,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,MonthlyIncome,NetWorth,InterestRate
0,-0.839119,2.517597,2,3,-0.752884,-1.218647,0.085231,0,0,-1.189451,0.171943,-0.248156,243.125239

In [18]:
x_train.columns

Index(['Age', 'CreditScore', 'EmploymentStatus', 'EducationLevel',
       'LoanAmount', 'LoanDuration', 'CreditCardUtilizationRate',
       'BankruptcyHistory', 'PreviousLoanDefaults', 'LengthOfCreditHistory',
       'MonthlyIncome', 'NetWorth', 'InterestRate'],
      dtype='object')

In [19]:
df['EmploymentStatus'].unique

<bound method Series.unique of 0        2
1        2
2        2
3        2
4        2
        ..
19995    2
19996    2
19997    2
19998    2
19999    2
Name: EmploymentStatus, Length: 20000, dtype: int64>

In [27]:
Predicted_Risk_Score = reg_model.predict(input_df)
Predicted_Risk_Score

array([57.33718091])

CLASSIFICATION MODEL

In [20]:
df_standardized['LoanApproved'].value_counts()

0    10761
1     3724
Name: LoanApproved, dtype: int64

In [21]:
x1=df_standardized[['RiskScore']]
y1=df_standardized[['LoanApproved']]

In [22]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size=0.2,random_state=42)

print('Shape of Training Features: ',x_train.shape)
print('Shape of Testing Features: ',x_test.shape)
print('Shape of Training Target: ',y_train.shape)
print('Shape of Testing Target: ',y_test.shape)

Shape of Training Features:  (11588, 13)
Shape of Testing Features:  (2897, 13)
Shape of Training Target:  (11588, 1)
Shape of Testing Target:  (2897, 1)

In [24]:
from sklearn.ensemble import RandomForestClassifier
clf_model = RandomForestClassifier()
clf_model.fit(x1_train, y1_train.values.ravel())

RandomForestClassifier()

In [25]:
x1_train

       RiskScore
17307       45.6
250         51.0
17297       49.0
16392       50.0
3052        40.8
...          ...
7189        54.0
18559       54.0
7474        56.0
1169        52.0
10062       51.0

[11588 rows x 1 columns]

In [28]:
Predicted_Risk_Score

array([57.33718091])

In [29]:
Predicted_LoanApproval_Status = clf_model.predict([Predicted_Risk_Score])
if Predicted_LoanApproval_Status == 0:
  print("Rejected")
else:
  print("Approved")

Rejected

c:\Users\Pc\anaconda4\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [30]:
import pickle 
with open('LGBMRegressor_model.pkl','wb') as file:
  pickle.dump(reg_model,file)

In [31]:
with open('Scaler.pkl','wb') as file:
  pickle.dump(scaler,file)

In [34]:
# Save classification model
with open('RandomForest_model.pkl','wb') as f:
  pickle.dump(clf_model,f)